# Local dev conda dependencies
channels:
- defaults
- conda-forge
dependencies:
- conda
- python=3.10
- anaconda-anon-usage
- anaconda-client >=1.13.0
- tox=3
- tox-conda
- pip
- pip:
    - "-e .[dev]"
