{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: anaconda-auth-bundle
  version: {{ version }}

source:
  path: ..

outputs:
  - name: {{ name }}
    build:
      script:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{version}} python -m pip install . -vv
      noarch: python

    requirements:
      host:
        - python {{ project['requires-python'] }}
        - pip
        {% for dep in pyproject['build-system']['requires'] %}
        - {{ dep.lower() }}
        {% endfor %}
      run:
        - python {{ project['requires-python'] }}
        {% for dep in project['dependencies'] %}
        - {{ dep.lower() }}
        {% endfor %}
      run_constrained:
        - {{ pin_subpackage("anaconda-cloud-auth", exact=True) }}
        - conda-token >=0.7.0
    test:
      imports:
        - anaconda_auth
      commands:
        - python -c "from anaconda_auth import __version__; assert __version__ == '{{ version }}'"

  - name: anaconda-cloud-auth
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ project['requires-python'] }}
      imports:
        - anaconda_auth
        - anaconda_cloud_auth
      commands:
        - python -c "from anaconda_auth import __version__; assert __version__ == '{{ version }}'"
        - python -c "from anaconda_cloud_auth import __version__; assert __version__ == '{{ version }}'"

about:
  home: {{ project['urls']['repository'] }}
  summary: {{ project['description'] }}
  license: {{ project['license']['text'] }}
  license_file: LICENSE
